 CREATE TABLE BANK_TRANSACTION 
   (	"WHEN" DATE, 
	"DESCRIPTION" VARCHAR(2000), 
	"AMOUNT" NUMBER, 
	"WHO" VARCHAR(20), 
	"FYE" NUMBER, 
	"BANK" VARCHAR(50), 
	"ID" NUMBER primary key
   ) ;
   
   --------------------------------------------------------
--  File created - Saturday-September-30-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANK_TRANSACTION
--------------------------------------------------------

   CREATE TABLE CAT_TRANS_LNK 
   ("CATEGORY" VARCHAR(50), 
	"SEARCH" VARCHAR(200), 
	"USERS" VARCHAR(20)
   ) ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE CATEGORY 
   (	"NAME" VARCHAR(50), 
	"TYPE" VARCHAR(50), 
	"DEDUCTION" INTEGER, 
	"USERS" VARCHAR(50), 
	"SORT_ORDER" INTEGER
   ) ;
   


Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','POINT LOOKOUT BLUE R','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER DEBIT TO 450201286 REFERENCE NO 54613381 tax','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('SERVICE VW','RABY BAY TYRE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','FOREIGN CURRENCY CONVERSION FEE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','Agnes Water','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','ISLAND FRUIT BARN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','UQ TRAFFIC AND PARK','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','SKIPS FIRST STOP DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','IGA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','MITRE 10','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','CLEVELAND FRUIT BARN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','Activeskin Solutions','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','POINT LOOKOUT NEWS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Bell speedy bell - DIRECT CREDIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 450201286 REF NO 54529402 surf trip','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET EXTERNAL TRANSFER TO 923100 036362017 REF NO 17695631 ing startup','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','HARVEY NORMAN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','EW LEAF NATRL THRPIES WYNNUM','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','LOGAN HEART SERVICE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','EW LEAF','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CHARITY','NIGHT NINJAS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TRAVEL','BNEAIR BNEAIR Int LS Dep Brisban - Receipt 5669ATM owner fee of $2.50 charged by BNEAIR BNEAIR Int LS Dep BrisbanDate 30 Jan 2017 Time 9:27PM Card 462263xxxxxx4176','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER DEBIT TO 29272623','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','BAC PARKING','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','MOGO TRADING','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','MANNYS DELI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','LIQUORLAND','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','EARLY BAIT AND TACKL ULLADULLA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','ULLADULLA PHARMAC','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','SIX SISTERS LAKES ENTRAN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','THE COFFEE CLUB','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','CGS COFFEE & GRUB BETHANIA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Stradbroke Pharmacy Dunwich','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','BRUNSWICK VILLAGE GREEN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','DELUXE LINEN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','MICKS NUT SHOP','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','BEAUTY AT BARDON','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Initial Deposit - Internal Transfer - Receipt 696801 Savings Maximiser 0089263069','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','Esther Lodge H 3118973 TATHRA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','INTERNET EXTERNAL TRANSFER TO 923100 035245805 REF NO 22736460 Building supplies','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','SQ*STRANDED','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','CAFE ARABICA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','DYMOCKS CARINDALE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','SQ*STARFISH STUDIO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BARGE','Stradbroke F*','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL VW','BP ','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','COLES','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','VISA CASH ADVANCE FEE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','BUPA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','STRADDIE SUPER SPORT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Dr D Turkiewicz Greenslope','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','MALOUF GROUP PHMCY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','MYER LOGAN LOGANHOLME','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','SPAR MACLEAN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','MACLEAN CELLARS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','BATHURST REGN COUNCIL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ART','WITZIG & ASSOCIATES','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','CafeEscargot','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL VW','CALTEX','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','EL CAMINODE BULLI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','THE BEAN & LEAF CAFE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','SHEESH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','014274347582599 REF NO 9458540','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','LA DOLCE VITA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','Spirithouse Yandina','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TRAVEL','TIGER AIR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','THAISONS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','CW CORNUBIA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','GRAND VIEW HOTEL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','THE ORMISTON BAKERY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','WATERFORD DIS FRUIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','LA BOUCHE WELLINGTON','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','GLOBAL FINE FOOD ASHGROVE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PHONE','OFFICEWORKS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','Stradbroke Hotel','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL VW','QLD MOTORWAYS MANAGEME EIGHT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','MANNYS FRUIT MARKET','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','WOODFIRED ETC TATHRA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','DRAKE SUPERMARKET','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','VISA CASH ADV 00000000000/HT MERCURE PADANG  21/01 ID 1250000.000 IDR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','REV SIMPLY ME CLEVELAND  CLEVELAND AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','WATERFORD DISCOUNT  HILTON  AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','TRANSLINK BRISBANE  18/02 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL TOYOTA','STRADDIE ROADHOUSE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','BOOKDEPOSITORY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('WATER TAXI','STRADBROKE FLYER WATER','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('AIR BNB','CITIBANK EUROPE Worldpay AP Ltd','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Queensland X-Ray','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','BRUNSWICKVILLAGEGREENS BRUNSWICK HE 07/12 NS 47.110 AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','STRADBROKE ISLAND BUT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','RMS*Takarakka Bush R 0383999462 26/03 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','Surfstreet Point Lookou 28/12 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','UQ MORETON BAY STATI  NORTH STRA AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','MOSSOPS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','STRADDIE NEWS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','014218 254857661 REF NO 13269380 Inv* 3884','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','SQ *MADE ON MINJERRIBA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Dr D Turkiewicz   Greenslope AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','INTERNET EXTERNAL TRANSFER TO 014274 347582599 REF NO 94585401 BELL GL 108898','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ART','Salt water Mur','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','Esther Lodge H3118973 TATHRA2  AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','DAX AUST PTY LTD TA BRUNSWICK HE 07/12 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','RUFUS KING SEAFOODS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','BELL ins isp - DIRECT CREDIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','BRENLAW PTY LTD   ABERDEEN  AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TRAVEL','OEH WOMBEYAN CAVES TARALGA  15/12 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','NORTH STRADBROKE FOO  DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','014218 254857661 REF NO 51495391 Inv* 3669','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','NORTH STRADBROKE FOO DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','POST DUNWICH LPO DUNWICH  03/08 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','CWH CORNUBIA       AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','MIRAJE HOME DECOR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','SIMPLY ME CLEVELAND','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','WOOLWORTHS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','VISA CREDIT  TRANSLINK BRISBANE  26/04 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','NORTH STRADBROKE FOODW DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CHARITY','PCYC NAT LOTTERIE QLD WHALAN  02/12 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TRAVEL','Tickets.com Pty Ltd th WollongNS 09/09 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','PILLOW TALK PTY LTD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 24243293 REF NO 37919321 vw','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','UQ MORETON BAY STATI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','SHOE IN PTY LTD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','BELL - DIRECT CREDIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','PT LOOKOUT SOUVENIRS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 450201286 REF NO 59770341 xmas','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','STUDIO DIAMONDS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 29272623 REF NO 78320500','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER DEBIT TO 29272623 REFERENCE NO 4865912 EFFECTIVE DATE 16/09/2016','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL INS REFUND','MCARE BENEFITS 003079056 EYWQ - DIRECT CREDIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','BARDON SMILES PTY LTD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL INS REFUND','MCARE BENEFITS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HAIR AND BEAUTY','SQ *STRANDED ON STRAD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','ATM Rebate - Receipt 6368We paid the ATM fee for you!','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CWTH SUPER','CSC       60640077PS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','ATM Rebate','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Internal Transfer','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','DCP-Foodworks Point LooSt radbroke Is','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','LITTLE PRINCE EATIN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','SQ *STARFISH STUDIO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Transfer to G C BELL - Receipt 211301 To 484799 24243293 - Transfer to G C BELL - Receipt 211301 To 484799 24243293','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CLOTHING','DBS MENWEAR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('POST','POST  POINT LOOKOUT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','1 - Internal Transfer - Receipt 235378 Savings Maximiser 0089263069','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','BELL GC     ing startup - Receipt 101688','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','rates and power - Transfer to G C BELL - Receipt 21490 To 484799 24243293','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','R L KOPPENOL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','INTERNET EXTERNAL TRANSFER TO 064466 010074783 REF NO 86207430 BELL, GC','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','STRADDIE BAKERY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','STRADBROKE RSL DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','ROLLESTON GENERAL ST ROLLESTON','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','CARNARVON GORGE WILD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','SUNCORP BANK CLEVELAND QL - Receipt 8307ATM owner fee of $2.00 charged by SUNCORP BANK CLEVELAND QLDate 09 Jun 2017 Time 1:20PM Card 462263xxxxxx4176','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','BELL GLENN COLIN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','STARLIGHT MOTOR INN ROMA - EFTPOS Purchase - Receipt 278Date 04 Jun 2017 Time 3:41PM Card 462263xxxxxx4176','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REGO SUBARU','TMR REG RENEW 48272      10249312514707 - BPAY Bill Payment - Receipt 9850 To TMR REG RENEW 48272 10249312514707','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Transfer to G C BELL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','Orchid Floral Design','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','ASPIRATIONAL HOSPITA CHILDERS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','MPH REDLANDS CLEVELAND - EFTPOS Purchase - Receipt 30085Date 18 Apr 2017 Time 1:11PM Card 462263xxxxxx4176','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 29272623 REF NO 16113311','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','CWH CAPALABA ','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','L/LAND','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','INTERNET TRANSFER DEBIT TO 509220860 REFERENCE NO 27898441 stuff','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','4 SIMPLICITY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','1ST CHOICE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 29272623 REF NO 78058462','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 29272623','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','PS SANDHU PTY LTD  ABERDEEN  AU - EFTPOS WDL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','INTERNET EXTERNAL TRANSFER TO 014218 254857661 REF NO 13269380 Inv* 3884','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','INTERNET EXTERNAL TRANSFER TO 014218 254857661 REF NO 51495391 Inv* 3669','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET EXTERNAL TRANSFER TO 923100 035245805 REF NO 58755310 Merry Xmas','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REPAIRS','INTERNET EXTERNAL TRANSFER TO 034115 000273629 REF NO 69043380 622507','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REGO SUBARU','TMR REG RENEW 48298      10245850093286 - BPAY Bill Payment - Receipt 535867 To TMR REG RENEW 48298 10245850093286','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','QUEENSLAND TRANSPORT  CLEVELAND AU - EFTPOS WDL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','R.L KOPPENOL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 509220860 REF NO 58883410 close','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('RATES','BPAY DEBIT VIA INTERNET REDLAND COUNCIL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('POWER','BPAY DEBIT VIA INTERNET LUMO ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOUSE INSURANCE','BPAY DEBIT VIA INTERNET RACQ INSURANCE REFERENCE NUMBER  3369','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PHONE','BPAY DEBIT VIA INTERNET TELSTRA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CREDIT CARD','BPAY DEBIT VIA INTERNET CITIBANK CREDITCARDS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('RACQ','BPAY DEBIT VIA INTERNET RACQ     92000093157329 REFERENCE NUMBER 32028391','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('POWER','BPAY DEBIT VIA INTERNET RED ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GAS','BPAY DEBIT VIA INTERNET ORIGIN ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','BPAY DEBIT VIA INTERNET SDRO PENALTIES  89460788327336 REFERENCE NUMBER 52889322','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','BPAY DEBIT VIA INTERNET','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTEREST','Interest Credit','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTEREST','Bonus Interest Credit','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','Initial Deposit - Receipt 696801 - From Orange Everyday','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('WHITE GOODS','JB HI FI - Visa Purchase - Receipt 171662In BRISBANE Date 30 Mar 2017 Card 462263xxxxxx4176','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Medicare Benefit','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('UQ','UNI OF QLD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MUSIC','ALBUMWORKS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','SHINGLE INN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('QSUPER','QSUPER','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','Sunburst Outdoor Livin','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TAX','ATO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CHARITY','World Vision','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','STRADBROKE ISLAN DBUT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','BUNNINGS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','WORDSMITHS CAFE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('QLD HEALTH','QUEENSLAND HEALT SALARY 00190392','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERNET','IINET','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','BCC ON-STREET PARKING','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','BCF','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','MAROOCHYDORE DISCOUN MAROOCHYDORE 10/08 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','NEWMARKET GARDENS CARA ASHGROVE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','DAN MURPHY''S','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','MURA TRAIN SUSHI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','WHALES WAY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','TAKARU NATIONAL PROP ROLLESTON','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','RED LOTUS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','REDLANDS INDIGISCAPE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','WHO GIVES A CRA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','OCEANIC GELATI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','SING''S ASIAN KITCHEN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','PADDINGTON HARDWARE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','923100035245805 REF NO 22736460 Building supplies','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','CHEMIST WAREHOUSE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','UQ MORETONBAY STATI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','LITTLE SHIP CLUB','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','ARBONNE EUROPE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','ORMISTON FAMILY PHAR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','STRADDIE SERVO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','UNITED CHURCHILL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','THE HIDDEN DONUT ABERDEEN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','ACCOUNT KEEPING FEE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','Cafe Escargot','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Invoice 18742 - Transfer to Dr V Swainsbury - Receipt 507237 To 084004 846163911','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('WITHDRAWAL','ATM WITHDRAWAL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','ATM OPERATOR FEE BALANCE ENQUIRY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('AIR BNB','ENVOY SERVICES','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','CLEVELAND TOBACCO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 29272623 REF NO 96934471','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','ATM OPERATOR FEE WITHDRAWAL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL VW','WESTSIDE PETROLEUM BRAIDWOOD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PHONE','VIRGIN MOBILE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','THE PRAWN SHACK','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BARGE','STRADBROKE FERRIES','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('SERVICE VW','AARONS MECHANICAL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('RATES','REDLAND COUNCIL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER DEBIT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('POWER','RED ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PHONE','TELSTRA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','BOBS SHOP','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','INTERNET TRANSFER CREDIT FROM 450201286 REF NO 90159710','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REGO VW','BPAY DEBIT VIA INTERNET TMR REG RENEW 48272 REFERENCE NUMBER  7099','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','Seymour St Newsagency','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','LITTLE PRINCE EATIN TRARALGON','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('SERVICE SUBARU','STRADBROKE AUTO','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Pt Lookout Pharmacy','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','JOHN TRUMAN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','PAPABUNZ MBL JAKARTA  21/01 ID 109200.000 IDR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','P&C T3 DT CENTRAL SINGAPORE 21/01 SG 111.100 SGD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('REGO TOYOTA','BPAY DEBIT VIA INTERNET TMR REG RENEW 48272 REFERENCE NUMBER  9779','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CREDIT CARD','CITIBANK CREDIT CARDS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','BAC PARKING ASCOT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','JR DUTY FRE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','LGB MEDICAL GREENSLOPES','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','ALDI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('POWER','LUMO ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GAS','ORIGIN ENERGY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTERBANK TRANSFER','1 - Receipt 235378 - From Orange Everyday','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','Queensland XRay','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','D P CARROL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','STARBUCKS','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TRAVEL','JETSTAR','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','RAFFERTY''S CAFE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PARKING','METRO PARKING','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','THE REJECT SHOP','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','NOREENS SEASIDE SHOP','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('BANK FEE','TRANSACTION FEE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','BOOK DEPOSITORY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('CHOOKS','CAPALABA PRODUCE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOUSE INSURANCE','RACQ INSURANCE REFERENCE NUMBER 3369','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','STRADDIE BAKERY DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('INTEREST','CREDIT INTEREST','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','STRADBROKE PHARMACY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','STRADDIE SERVO DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('RACQ','RACQ 92000093157329 REFERENCE NUMBER 32028391','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','STRADDIE SUPER SPORT DUNWICH','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('MEDICAL','SURF STREET HEALTH POINT LOOKOU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','WYNNUM FRUIT AND VEG','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','WRAY ORGANIC CLEVE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('FISHING','AMITY POINT INVEST','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','ARRIVEDERCI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('SERVICE SUBARU','STRADBROKE AUTOMOTIV','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','BOOKTOPIA','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ALCOHOL','DAN MURPHY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('TAX_AGENT','BIRD WALKER MCDONALD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','PSS AND HU PTY LTD ABERDEEN','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','BOOLARRA STORE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','DAX AUST PTY LTD TA BRUNSWICKHE','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HOMEWARE','S/ARMY','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','FISHES AT THE POINT','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('DINING','EL CAMINO DE BULLI','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','OEH DIAMOND HEAD CAM','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('PETROL VW','SHELL','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('ACCOM','SAPPHIRE RESORT TH BRISBANQL 31/01 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('GROCERIES','EGGINS LAURIETON NEWSA LAURIETON 07/12 AU AUD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('RACQ','RACQ EIGHT MILE PLAIN EIGHT MILE P','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('SERVICE TOYOTA','ABS CLEVELAND PTY LTD ORMISTON  AU','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','SANDBAG LTDWASTE 441189569183 12/09 GB 12.990 USD','Glenn Jennie');
Insert into GB.CAT_TRANS_LNK (CATEGORY,SEARCH,USERS) values ('HARDWARE','923100 035245805 REF NO 22736460 Building supplies','Glenn Jennie');
REM INSERTING into GB.CATEGORY
SET DEFINE OFF;
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HAIR AND BEAUTY','LIFESTYLE',0,'Glenn Jennie',55);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTERBANK TRANSFER','TRANSFER',0,'Glenn Jennie',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CWTH SUPER','INCOME',0,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('QLD HEALTH','INCOME',1,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CLOTHING','FOOD',0,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('POST','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TAX','TAX',0,'Glenn Jennie',88);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MEDICAL INS REFUND','REFUND',0,'Glenn Jennie',77);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HARDWARE','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WITHDRAWAL','WITHDRAWAL',0,'Glenn Jennie',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ACCOM','RECREATION',0,'Glenn Jennie',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('DINING','FOOD',0,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WHITE GOODS','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BARGE','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('FINE','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL TOYOTA','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MUSIC','RECREATION',0,'Glenn Jennie',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('QSUPER','INCOME',0,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE VW','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CHARITY','DEDUCTION',1,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ART','HOMEWARE',0,'Glenn Jennie',44);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WATER TAXI','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PHONE','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('AIR BNB INSURANCE','EXPENSE',1,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MEDICAL','DEDUCTION',1,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTERNET','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TAX_AGENT','DEDUCTION',1,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ALCOHOL','FOOD',0,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('POWER','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PARKING','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL VW','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO VW','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HOUSE INSURANCE','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BUS','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('RATES','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('GAS','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('FISHING','RECREATION',0,'Glenn Jennie',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO TOYOTA','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TRANSFER','TRANSFER',0,'Glenn Jennie',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('DEPOSIT','DEPOSIT',0,'Glenn Jennie',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BANK FEE','DEDUCTION',1,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('AIR BNB','INCOME',0,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('UQ','INCOME',0,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE TOYOTA','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO SUBARU','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL SUBARU','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE SUBARU','CAR',0,'Glenn Jennie',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('GROCERIES','FOOD',0,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CREDIT CARD','TRANSFER',0,'Glenn Jennie',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REPAIRS','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HOMEWARE','EXPENSE',0.5,'Glenn Jennie',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TRAVEL','TRAVEL',0,'Glenn Jennie',68);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CHOOKS','FOOD',0.5,'Glenn Jennie',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('RACQ','TRANSPORT',0,'Glenn Jennie',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTEREST','INCOME',1,'Glenn Jennie',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HAIR AND BEAUTY','LIFESTYLE',0,'Jackson',55);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTERBANK TRANSFER','TRANSFER',0,'Jackson',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CWTH SUPER','INCOME',0,'Jackson',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('QLD HEALTH','INCOME',1,'Jackson',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CLOTHING','FOOD',0,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('POST','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TAX','TAX',0,'Jackson',88);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MEDICAL INS REFUND','REFUND',0,'Jackson',77);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HARDWARE','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WITHDRAWAL','WITHDRAWAL',0,'Jackson',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ACCOM','RECREATION',0,'Jackson',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('DINING','FOOD',0,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WHITE GOODS','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BARGE','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('FINE','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL TOYOTA','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MUSIC','RECREATION',0,'Jackson',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('QSUPER','INCOME',0,'Jackson',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE VW','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CHARITY','DEDUCTION',1,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ART','HOMEWARE',0,'Jackson',44);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('WATER TAXI','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PHONE','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('MEDICAL','DEDUCTION',1,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTERNET','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TAX_AGENT','DEDUCTION',1,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('ALCOHOL','FOOD',0,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('POWER','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PARKING','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL VW','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO VW','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HOUSE INSURANCE','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BUS','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('RATES','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('GAS','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('FISHING','RECREATION',0,'Jackson',66);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO TOYOTA','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TRANSFER','TRANSFER',0,'Jackson',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('DEPOSIT','DEPOSIT',0,'Jackson',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('BANK FEE','DEDUCTION',1,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('UQ','INCOME',0,'Jackson',11);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE TOYOTA','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REGO SUBARU','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('PETROL SUBARU','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('SERVICE SUBARU','CAR',0,'Jackson',70);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('GROCERIES','FOOD',0,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CREDIT CARD','TRANSFER',0,'Jackson',99);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('REPAIRS','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('HOMEWARE','EXPENSE',0.5,'Jackson',22);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('TRAVEL','TRAVEL',0,'Jackson',68);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('CHOOKS','FOOD',0.5,'Jackson',33);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('RACQ','TRANSPORT',0,'Jackson',67);
Insert into GB.CATEGORY (NAME,TYPE,DEDUCTION,USERS,SORT_ORDER) values ('INTEREST','INCOME',1,'Jackson',11);
--------------------------------------------------------
--  DDL for Index BANK_TRANSACTION_PK
--------------------------------------------------------

  ALTER TABLE BANK_TRANSACTION" ADD CONSTRAINT "BANK_TRANSACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE BANK_TRANSACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAT_TRANS_LNK
--------------------------------------------------------

  ALTER TABLE CAT_TRANS_LNK" ADD CONSTRAINT "CAT_TRANS_LNK_PK" PRIMARY KEY ("SEARCH", "USERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE CAT_TRANS_LNK" MODIFY ("USERS" NOT NULL ENABLE);
  ALTER TABLE CAT_TRANS_LNK" MODIFY ("SEARCH" NOT NULL ENABLE);
  ALTER TABLE CAT_TRANS_LNK" MODIFY ("CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE CATEGORY
  ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("NAME", "USERS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE CATEGORY" MODIFY ("USERS" NOT NULL ENABLE);
  ALTER TABLE CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CAT_TRANS_LNK
--------------------------------------------------------

  ALTER TABLE CAT_TRANS_LNK" ADD CONSTRAINT "CAT_TRANS_LNK_FK1" FOREIGN KEY ("CATEGORY", "USERS")
	  REFERENCES CATEGORY" ("NAME", "USERS") ENABLE;
